# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
    source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Path to your Oh My Zsh installation.
export ZSH="$HOME/.oh-my-zsh/"

ZSH_THEME="powerlevel10k/powerlevel10k"

# Init Bash autocomplete
autoload -U bashcompinit
bashcompinit

# Disable changing directory without "cd"
unsetopt autocd
# share history between sessions
setopt share_history
# ignore blank commands
setopt  HIST_REDUCE_BLANKS

# Uncomment the following line if pasting URLs and other text is messed up.
DISABLE_MAGIC_FUNCTIONS="true"

# Indicates that Zsh is still processing a completion request
COMPLETION_WAITING_DOTS="true"
COMPLETION_WAITING_DOTS="%F{yellow}waiting...%f"

# Add timestamp to history entries
HIST_STAMPS="%d/%m/%Y %H:%M:%S"

# Plugins
plugins=(
    fzf
    ssh-agent
    sudo
    z
    zsh-autosuggestions
    zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh

# fzf integration
export FZF_DEFAULT_COMMAND="rg --files --follow --hidden --glob '!.git'"
export FZF_DEFAULT_OPTS="--highlight-line --ansi --bind 'ctrl-/:change-preview-window(down|hidden|)'"
export FZF_ALT_C_OPTS="--walker-skip .git,node_modules,venv --preview 'tree -C {}'"
export FZF_CTRL_R_OPTS="--wrap --preview-window down:5:hidden:wrap --reverse"
export FZF_CTRL_T_OPTS="--preview='batcat -n --color=always {}'"

# import zsh custom functions
for CUSTOM in $HOME/.zsh-customs/*; do
	[ -f "$CUSTOM" ] && . "$CUSTOM"
done

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
